MODEL:
  STYLE_ENCODER_LAYERS: 3
  NUM_IMGS: 15
  IN_CHANNELS: 4
  OUT_CHANNELS: 4
  NUM_RES_BLOCKS: 1
  NUM_HEADS: 4
  EMB_DIM: 512
SOLVER:
  BASE_LR: 0.0001
  EPOCHS: 160
  WARMUP_ITERS: 10000
  TYPE: AdamW  # TODO, support optional optimizer
  GRAD_L2_CLIP: 1.0
TRAIN:
  TYPE: train
  IMS_PER_BATCH: 32
  SNAPSHOT_BEGIN: 0
  SNAPSHOT_ITERS: 1
  VALIDATE_BEGIN: 0
  VALIDATE_ITERS: 1
  SEED: 1001
  IMG_H: 64
  IMG_W: 64
TEST:
  TYPE: test
  IMS_PER_BATCH: 32
  IMG_H: 64
  IMG_W: 64
DATA_LOADER:
  NUM_THREADS: 2
  IAMGE_PATH: ./data/Devanagari Dataset/style
  STYLE_PATH: ./data/Devanagari Dataset/style
  LAPLACE_PATH: ./data/Devanagari Dataset/laplace